$install_apachehttpd_script = <<-SCRIPT
echo Provisioning apache2...
apt update
apt install -y apache2
echo "<h1>Hello from HOST machine</h1>" > /var/www/html/index.html
sed -i -e 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
service apache2 restart
echo Provisioning apache2... finished
SCRIPT

Vagrant.configure("2") do |config|
  #config.vm.provider "virtualbox" do |v|
    #v.gui = true
  #end

  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.provision "shell", before: :all, inline: $install_apachehttpd_script

  # docker build --tag asclab/vuln/jdwp-demo
  # docker run --privileged --publish 80:80 --publish 8000:8000 asclab/vuln/jdwp-demo
  config.vm.provision "docker" do |d|
    d.build_image "/vagrant/app", args: "--tag asclab/vuln/jdwp-demo"
    d.run "asclab/vuln/jdwp-demo", args: "--privileged --publish 80:80 --publish 8000:8000"
  end

end
